/* ============================================================================
   THE EVERYDAY EDIT  —  SITE DATA  (THIS IS THE ONLY FILE YOU NEED TO EDIT)
   ----------------------------------------------------------------------------
   • Change text, prices, affiliate links, images and CTAs below.
   • Do NOT edit index.html for normal updates — everything lives here.
   • After editing: save this file, refresh the page. That's it.

   QUICK EDITS:
   - Price:            change  price: "from €19"
   - Affiliate link:   change  link:  "https://..."     (paste your real link)
   - Image:            set     image: "images/neck-fan.jpg"   (drop file in /images)
   - Hide a product:   set     status: "paused"
   - Reorder products: change  priority: (higher number = shown first)
   - Change a CTA:     change  cta:   "Check it out →"
   - Move a product:   change  category: (must match a category id below)

   Status values:  "active"  = shown   |  "testing" = shown + small tag
                   "paused"  = hidden
   The "affiliate" field is a note for YOU (which program pays best) — not shown.
============================================================================ */

const SITE = {
  brandName: "the everyday edit",
  metaTitle: "the everyday edit — useful viral finds, only the ones that are worth it",
  metaDescription:
    "We test the viral products blowing up on TikTok & Reels, keep the ones that are actually useful.",

  // Top scrolling bar. Keep it HONEST — no fake countdowns, no fake free shipping.
  offerBar: [
    "Curated viral finds — only the ones actually worth it",
    "Updated daily · independent picks",
    "Available across the EU",
  ],

  // Quick nav (kept for reference; the site mainly uses the category bar + menu).
  nav: [
    { label: "summer cooling", href: "#summer-cooling" },
    { label: "beauty & wellness", href: "#beauty-wellness" },
    { label: "room & lighting", href: "#room-lighting" },
    { label: "tech & gadgets", href: "#tech-gadgets" },
    { label: "how we choose", href: "#how" },
  ],

  hero: {
    eyebrow: "VIRAL FINDS, MINUS THE JUNK",
    headline: "The useful stuff you keep seeing — in one place.",
    sub: "We test the products blowing up on TikTok & Reels, keep the ones that are actually good.",
    ctaPrimary: "See this summer's picks →",
    ctaPrimaryHref: "#summer-cooling",
    ctaSecondary: "How we choose",
    ctaSecondaryHref: "#how",
  },

  // CATEGORIES (the bar on top). id must match each product's "category".
  categories: [
    { id: "summer-cooling", chip: "🔥 Beat the heat", label: "Summer cooling",
      blurb: "Wearable fans, misting fans and cooling gear for heatwaves and no-AC days." },
    { id: "beauty-wellness", chip: "✨ Beauty & wellness", label: "Beauty & wellness",
      blurb: "At-home glow, scent and feel-good devices." },
    { id: "room-lighting", chip: "💡 Room & lighting", label: "Room & lighting",
      blurb: "Lighting that makes a room (or a video) look good." },
    { id: "tech-gadgets", chip: "📱 Tech & gadgets", label: "Tech & gadgets",
      blurb: "Small upgrades that punch above their price." },
    { id: "home-pet", chip: "🏠 Home & pet", label: "Home & pet",
      blurb: "Quick wins for a cleaner home and happier pets." },
    { id: "car-travel", chip: "🚗 Car & travel", label: "Car & travel",
      blurb: "Make the car cooler, comfier and better-looking." },
  ],

  // "How we choose" / trust row. No fake reviews — this is the honesty section.
  trust: [
    { emoji: "🔍", title: "We actually vet them", text: "We dig through the viral stuff, check real reviews, and skip what doesn't hold up." },
    { emoji: "🇪🇺", title: "EU-friendly picks", text: "Things you can get in Germany, Austria, the Netherlands, Czechia, Poland and nearby." },
    { emoji: "💬", title: "Honest about money", text: "Some links are affiliate links. We only list things we'd recommend anyway. Your price never changes." },
    { emoji: "🔄", title: "Updated daily", text: "New winners in, dead trends out. This page is a living list, not a dusty store." },
  ],

  email: {
    enabled: true,
    title: "Get next week's finds",
    text: "One short email when we add new winners. No spam, unsubscribe anytime.",
    placeholder: "your@email.com",
    button: "Keep me posted",
    action: "",
  },

  faq: [
    { q: "Do you sell these products?",
      a: "No. We're a discovery page. We point you to a store where you can get it and you buy there directly. Payment, shipping and returns are handled by that store." },
    { q: "Are the links affiliate links?",
      a: "Some are. If you buy through them we may earn a small commission at no extra cost to you — it never changes your price." },
    { q: "How do you choose the products?",
      a: "We look for viral products that are genuinely useful, we buy & try them in person and also check other reviews and EU availability, and drop the ones that don't hold up." },
    { q: "Which countries can order?",
      a: "Most picks are available across the EU. Exact availability and shipping times depend on the store you're sent to." },
  ],

  // Contacts (shown in the left menu). Add your real handles when ready.
  contacts: [
    { label: "Email", value: "hello@yourdomain.com", href: "mailto:hello@yourdomain.com" },
    { label: "Instagram", value: "@vinral", href: "#" },
    { label: "TikTok", value: "@vinral", href: "#" },
    { label: "Facebook", value: "vinral", href: "#" },
  ],

  footer: {
    columns: [
      { title: "explore", links: [
        { label: "summer cooling", href: "#summer-cooling" },
        { label: "beauty & wellness", href: "#beauty-wellness" },
        { label: "room & lighting", href: "#room-lighting" },
        { label: "car & travel", href: "#car-travel" },
      ]},
      { title: "about", links: [
        { label: "how we choose", href: "#how" },
        { label: "faqs", href: "#faq" },
        { label: "contact", href: "mailto:hello@yourdomain.com" },
      ]},
    ],
    contactEmail: "hello@yourdomain.com",
    disclaimer:
      "Independent product discovery. Not affiliated with TikTok, Instagram, Meta or the brands shown. Some links are affiliate links — if you buy through them we may earn a small commission at no extra cost to you.",
  },

  affiliateDisclosure:
    "Heads up: some links on this page are affiliate links. If you buy through them, we may earn a small commission — at no extra cost to you. We only list things we genuinely think are useful.",
};

/* ============================================================================
   PRODUCTS (17). Each has marketing fields (shown) + ops fields (for you).
============================================================================ */

const PRODUCTS = [
  /* ---------- BEAUTY & WELLNESS ---------- */
  {
    id: "led-face-mask",
    productName: "LED light face mask",
    category: "beauty-wellness",
    emoji: "💆",
    shortHook: "A 10-minute LED light routine for your skin.",
    painPoint: "Pricey facials and complicated routines you never keep up with.",
    mainBenefit: "A wearable LED light mask you use for about 10 minutes at home — built to fit an easy skincare routine.",
    bestFor: "At-home skincare fans",
    price: "from €49",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Editor pick",
    cta: "Check it out →",
    status: "active",
    priority: 96,
    riskNote: "Higher ticket = better payout. Check CE/electrical. Beauty programs pay more than gadgets.",
    complianceClaim: "Cosmetic skincare device for appearance only. No acne, anti-ageing or medical/treatment claims.",
    adAngle: "'My 10-minute glow routine' — get-ready-with-me.",
    targetAudience: "18–40, skincare & self-care, gifting",
    targetCountries: ["DE", "AT", "NL"],
    affiliate: "Amazon EU (Beauty, up to ~10%) or a brand program via Awin",
  },
  {
    id: "perfume-set",
    productName: "Perfume discovery set",
    category: "beauty-wellness",
    emoji: "🧴",
    shortHook: "Try 5–10 scents before you commit to a full bottle.",
    painPoint: "Full bottles are expensive and risky to blind-buy online.",
    mainBenefit: "A discovery set lets you test multiple scents at home, then buy only the one you actually love.",
    bestFor: "Anyone tired of blind-buying perfume",
    price: "from €20",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Smart buy",
    cta: "Browse sets →",
    status: "active",
    priority: 78,
    riskNote: "Higher intent + better beauty commissions = stronger money driver. Lean on the anti-blind-buy angle.",
    complianceClaim: "Helps you sample scents. No claims that a scent attracts people or guarantees compliments.",
    adAngle: "Stop spending €100 on a bottle you end up hating — test first.",
    targetAudience: "18–45, fragrance-curious, gift buyers",
    targetCountries: ["DE", "AT", "NL"],
    affiliate: "Amazon EU (Beauty, up to ~10%) or a brand program via Awin",
  },
  {
    id: "hair-trio",
    productName: "Hair texture trio",
    category: "beauty-wellness",
    emoji: "💈",
    shortHook: "Flat hair to full texture in a few minutes.",
    painPoint: "Fine or long hair goes flat fast and loses shape by midday.",
    mainBenefit: "A simple 3-step combo — sea-salt spray, texture powder and matte clay — built for grip, lift and a natural matte finish.",
    bestFor: "Fine, flat or long hair",
    price: "from €19",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Editor pick",
    cta: "See the trio →",
    status: "active",
    priority: 74,
    riskNote: "Good before/after demo + bundle potential. Strong evergreen grooming angle.",
    complianceClaim: "Designed to add texture and hold. Not a hair-growth or regrowth product.",
    adAngle: "The 3 products behind the effortless 'just-styled' look.",
    targetAudience: "16–35, men's grooming + fine-hair styling",
    targetCountries: ["DE", "AT", "NL", "CZ", "PL"],
    affiliate: "Amazon EU (Beauty, up to ~10%) or a brand program via Awin",
  },
  {
    id: "posture-corrector",
    productName: "Posture corrector",
    category: "beauty-wellness",
    emoji: "🧍",
    shortHook: "A gentle reminder to stop slouching at your desk.",
    painPoint: "Hours at a desk leave you hunched and stiff.",
    mainBenefit: "An adjustable, discreet posture support designed to remind you to sit and stand tall.",
    bestFor: "Desk workers, students",
    price: "from €19",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Desk fix",
    cta: "See it →",
    status: "active",
    priority: 66,
    riskNote: "Low-mid payout. Keep claims careful (no medical).",
    complianceClaim: "Posture-support aid. Not a medical device; doesn't treat or cure any condition.",
    adAngle: "Desk-posture check — wear it ~30 min a day.",
    targetAudience: "20–45, office workers, students",
    targetCountries: ["DE", "AT", "NL", "CZ", "PL"],
    affiliate: "Amazon EU (~3–4%) or AliExpress (~6%)",
  },

  /* ---------- SUMMER COOLING ---------- */
  {
    id: "misting-fan",
    productName: "Misting handheld fan",
    category: "summer-cooling",
    emoji: "💦",
    shortHook: "A handheld fan with a fine water mist for extra cooling.",
    painPoint: "A normal mini-fan just pushes hot air around.",
    mainBenefit: "Adds a light water mist for a fresher, cooler feel than a basic fan — pocket-sized and rechargeable.",
    bestFor: "Outdoors, festivals, hot rooms",
    price: "from €15",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Upgrade pick",
    cta: "Check it out →",
    status: "testing",
    priority: 95,
    riskNote: "Seasonal (Jun–Aug). Saturated — content quality decides. Low ticket = thin commission.",
    complianceClaim: "Gives a cooling feel; effect varies with conditions. No exact temperature-drop claims.",
    adAngle: "Normal fan vs misting fan — feel the difference on camera.",
    targetAudience: "16–35, festival/commuter/outdoor",
    targetCountries: ["DE", "AT", "NL", "CZ", "PL"],
    affiliate: "AliExpress (~6%) or Amazon EU (~3%)",
  },
  {
    id: "neck-fan",
    productName: "Portable neck fan",
    category: "summer-cooling",
    emoji: "🌀",
    shortHook: "Hands-free cooling that sits on your neck.",
    painPoint: "Commutes, queues and walks get brutal in summer heat.",
    mainBenefit: "A wearable, hands-free fan designed to keep air moving while you move — rechargeable, adjustable speeds.",
    bestFor: "Commuters, travel, festivals, no-AC days",
    price: "from €18",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Summer pick",
    cta: "Check it out →",
    status: "testing",
    priority: 90,
    riskNote: "Very saturated and seasonal. Differentiate on content angle (POV commute).",
    complianceClaim: "Helps you feel cooler. Does not prevent heatstroke or replace medical care.",
    adAngle: "Surviving the heatwave commute without melting — POV.",
    targetAudience: "16–40, commuters, travellers, festival-goers",
    targetCountries: ["DE", "AT", "NL", "CZ", "PL"],
    affiliate: "AliExpress (~6%) or Amazon EU (~3%)",
  },
  {
    id: "cooling-towel",
    productName: "Cooling towel",
    category: "summer-cooling",
    emoji: "🧊",
    shortHook: "Wet it, wring it, snap it — instant cool-down.",
    painPoint: "Workouts, walks and heat leave you overheated and sweaty.",
    mainBenefit: "A towel designed to feel cool when wet — reusable, for the gym, sport, the beach or hot days.",
    bestFor: "Gym, sport, outdoor work, beach",
    price: "from €12",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Gym favourite",
    cta: "See it →",
    status: "active",
    priority: 84,
    riskNote: "Lowest ticket — weakest economics alone. Good top-of-funnel content.",
    complianceClaim: "Provides a cooling feel when wet. Not a medical cooling device.",
    adAngle: "The cheap gym-bag essential for summer. Snap-to-activate demo.",
    targetAudience: "18–40, gym/sport, runners",
    targetCountries: ["DE", "AT", "NL", "CZ", "PL"],
    affiliate: "AliExpress (~6–8%) or Amazon EU (~3%)",
  },

  /* ---------- ROOM & LIGHTING ---------- */
  {
    id: "galaxy-projector",
    productName: "Galaxy & star projector",
    category: "room-lighting",
    emoji: "🌌",
    shortHook: "Fill your room with stars and a galaxy haze.",
    painPoint: "Plain ceilings and flat room lighting.",
    mainBenefit: "A projector that casts moving stars and a nebula glow for a calm, aesthetic room.",
    bestFor: "Bedrooms, gaming setups, kids' rooms",
    price: "from €27",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Aesthetic pick",
    cta: "See it →",
    status: "active",
    priority: 79,
    riskNote: "Saturated — content angle decides. Cheap = thin payout.",
    complianceClaim: "Decorative ambience. Not a sleep or therapy device.",
    adAngle: "Room glow-up reveal — lights off, galaxy on.",
    targetAudience: "12–28, students, gamers",
    targetCountries: ["DE", "AT", "NL", "CZ", "PL"],
    affiliate: "AliExpress (~6–8%) or Amazon EU (~3%)",
  },
  {
    id: "sunset-lamp",
    productName: "Sunset projection lamp",
    category: "room-lighting",
    emoji: "🌅",
    shortHook: "Turn any room into a sunset in seconds.",
    painPoint: "A plain room looks boring and flat on camera.",
    mainBenefit: "A projector lamp that casts a warm sunset glow for a cozy room, setup or content background.",
    bestFor: "Bedrooms, content backgrounds",
    price: "from €17",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Aesthetic pick",
    cta: "See it →",
    status: "active",
    priority: 80,
    riskNote: "Very saturated — content is everything. Cheap = thin payout.",
    complianceClaim: "For ambience and decoration. Not a therapy or 'mood-fixing' device.",
    adAngle: "The light that makes your room look expensive on camera.",
    targetAudience: "16–30, students, creators, renters",
    targetCountries: ["DE", "AT", "NL", "CZ", "PL"],
    affiliate: "AliExpress (~6–8%) or Amazon EU (~3%)",
  },
  {
    id: "led-wall-lights",
    productName: "Smart LED wall lights",
    category: "room-lighting",
    emoji: "🟪",
    shortHook: "Smart wall lights that turn a room into a setup.",
    painPoint: "Boring walls behind your desk or bed.",
    mainBenefit: "App-controlled LED wall panels/strips for a gaming or content-ready glow.",
    bestFor: "Gamers, desk setups, creators",
    price: "from €25",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Setup glow-up",
    cta: "See it →",
    status: "active",
    priority: 72,
    riskNote: "Check app quality; CE. Mid payout.",
    complianceClaim: "Decorative lighting; describe app features accurately.",
    adAngle: "Desk-setup transformation with smart lights.",
    targetAudience: "14–28, gamers, creators",
    targetCountries: ["DE", "AT", "NL", "CZ", "PL"],
    affiliate: "AliExpress (~6–8%) or Amazon EU (~3%)",
  },

  /* ---------- TECH & GADGETS ---------- */
  {
    id: "mini-projector",
    productName: "Mini portable projector",
    category: "tech-gadgets",
    emoji: "📽️",
    shortHook: "Turn any wall into a movie screen.",
    painPoint: "Small phone and laptop screens make movie nights underwhelming.",
    mainBenefit: "A compact projector for films, series and gaming on a big wall — plug in and play.",
    bestFor: "Movie nights, bedrooms, gaming",
    price: "from €69",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "High demand",
    cta: "Check it out →",
    status: "active",
    priority: 88,
    riskNote: "Higher ticket = strong payout. State real resolution/lumens honestly; EU plug.",
    complianceClaim: "Describe true specs (resolution, brightness). No exaggerated cinema claims.",
    adAngle: "€X bedroom cinema setup — POV movie night.",
    targetAudience: "16–35, students, couples, gamers",
    targetCountries: ["DE", "AT", "NL", "CZ", "PL"],
    affiliate: "Amazon EU (~3–5%, trusted for higher ticket) or AliExpress (~3–5%)",
  },
  {
    id: "mini-printer",
    productName: "Inkless pocket printer",
    category: "tech-gadgets",
    emoji: "🖨️",
    shortHook: "Pocket printer for photos, notes and stickers — no ink.",
    painPoint: "Photos stay stuck on your phone; notes get lost.",
    mainBenefit: "An inkless pocket printer that prints photos, study notes and stickers straight from your phone.",
    bestFor: "Students, journaling, planners",
    price: "from €34",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Trending",
    cta: "See it →",
    status: "active",
    priority: 76,
    riskNote: "Thermal paper is a consumable (repeat buy). Low-mid payout.",
    complianceClaim: "Inkless thermal printing; prints are monochrome unless stated.",
    adAngle: "Study-with-me / journal aesthetic — print straight from your phone.",
    targetAudience: "14–25, students, journaling",
    targetCountries: ["DE", "AT", "NL"],
    affiliate: "Amazon EU (~3–5%) or AliExpress (~5–8%)",
  },
  {
    id: "phone-case",
    productName: "Viral phone case",
    category: "tech-gadgets",
    emoji: "📱",
    shortHook: "Give your phone a glow-up that's actually useful.",
    painPoint: "Boring case, nowhere to keep your card, phone slips out of your hand.",
    mainBenefit: "Aesthetic cases with real utility — MagSafe, card holder, grip and standout designs people notice.",
    bestFor: "Anyone bored of a plain phone",
    price: "from €14",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Trending",
    cta: "See cases →",
    status: "active",
    priority: 68,
    riskNote: "Huge audience but enormous saturation + model-compatibility friction. Returns risk.",
    complianceClaim: "Styles and utility vary by model. Always check compatibility with your exact phone.",
    adAngle: "The case everyone asks you about — show the feature people don't expect.",
    targetAudience: "16–30, phone-style buyers, gift buyers",
    targetCountries: ["DE", "AT", "NL", "CZ", "PL"],
    affiliate: "Amazon EU (~3–4%) or AliExpress (~8%)",
  },

  /* ---------- HOME & PET ---------- */
  {
    id: "cordless-vacuum",
    productName: "Cordless handheld vacuum",
    category: "home-pet",
    emoji: "🧹",
    shortHook: "Cordless power for the car and quick home messes.",
    painPoint: "Crumbs in the car and small spills the big vacuum is overkill for.",
    mainBenefit: "A handheld cordless vacuum for the car, sofa and corners — rechargeable and light.",
    bestFor: "Car owners, quick clean-ups",
    price: "from €35",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Practical pick",
    cta: "See it →",
    status: "active",
    priority: 82,
    riskNote: "Battery shipping; CE. Mid payout. Very satisfying demo.",
    complianceClaim: "State real suction and run-time honestly.",
    adAngle: "Satisfying car deep-clean ASMR.",
    targetAudience: "25–50, drivers, parents",
    targetCountries: ["DE", "AT", "CZ", "PL", "NL"],
    affiliate: "Amazon EU (~3%) or AliExpress (~5%)",
  },
  {
    id: "pet-deshedding",
    productName: "Pet de-shedding brush set",
    category: "home-pet",
    emoji: "🐾",
    shortHook: "Brush out loose fur before it covers your home.",
    painPoint: "Pet hair on the sofa, clothes and basically everywhere.",
    mainBenefit: "A de-shedding brush plus a reusable hair remover for dogs and cats — oddly satisfying to use.",
    bestFor: "Dog & cat owners",
    price: "from €18",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Pet favourite",
    cta: "See it →",
    status: "active",
    priority: 70,
    riskNote: "Big pet niche. Mid-low payout; bundle for value.",
    complianceClaim: "Grooming tool. No skin-treatment or health claims.",
    adAngle: "Satisfying de-shed — look how much fur comes out.",
    targetAudience: "20–55, dog & cat owners",
    targetCountries: ["DE", "AT", "NL", "CZ", "PL"],
    affiliate: "Amazon EU (~3%) or AliExpress (~6%)",
  },

  /* ---------- CAR & TRAVEL ---------- */
  {
    id: "car-shade",
    productName: "Car windshield sun umbrella",
    category: "car-travel",
    emoji: "🚗",
    shortHook: "Stop your parked car turning into an oven.",
    painPoint: "Parked in the sun, the cabin, wheel and dashboard get unbearable.",
    mainBenefit: "A foldable umbrella-style shade that opens across the windshield to block sun and reduce heat build-up while you're parked.",
    bestFor: "Anyone who parks in the sun",
    price: "from €19",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Summer fix",
    cta: "See it →",
    status: "testing",
    priority: 92,
    riskNote: "Seasonal. Fit varies by windshield size — note dimensions. Strong before/after demo.",
    complianceClaim: "Helps reduce heat build-up; actual temperature depends on car, sun and time. No medical claims.",
    adAngle: "Open your car door without the wall of heat. Before/after.",
    targetAudience: "25–55, drivers, commuters, parents",
    targetCountries: ["DE", "AT", "CZ", "PL", "NL"],
    affiliate: "Amazon EU (~3%) or AliExpress (~6%)",
  },
  {
    id: "car-starlight",
    productName: "Car starlight headliner kit",
    category: "car-travel",
    emoji: "🌠",
    shortHook: "Give your car roof a starlight ceiling.",
    painPoint: "Plain, dull car interior at night.",
    mainBenefit: "A fibre-optic LED kit that adds a 'starry roof' glow to your car interior.",
    bestFor: "Car enthusiasts, night drives",
    price: "from €25",
    link: "#REPLACE-WITH-AFFILIATE-LINK",
    image: "",
    video: "",
    badge: "Car glow-up",
    cta: "See it →",
    status: "active",
    priority: 71,
    riskNote: "Install/fit varies by car; describe clearly. Mid payout.",
    complianceClaim: "Decorative only. Note it must not obstruct safe driving or visibility.",
    adAngle: "Installing a starlight headliner — before/after night reveal.",
    targetAudience: "18–35, car culture",
    targetCountries: ["DE", "AT", "CZ", "PL"],
    affiliate: "AliExpress (~6–8%) or Amazon EU (~3%)",
  },
];

// Make data available to the page. (Do not change these two lines.)
window.SITE = SITE;
window.PRODUCTS = PRODUCTS;
